jobName: "Kafka To Kafka"
source:
  kafka:
    bootstrapServers: localhost:9092
    topics: topic-source
    groupId: group-2024-10-28
    offsetInitializationType: EARLIEST
sink:
  kafka:
    bootstrapServers: localhost:9092
    topics: topic-sink