jobName: "Kafka To Kafka"
source:
  kafka:
    bootstrapServers: localhost:9092
    topics: source_topic
    groupId: group-2024-10-28
    offsetInitializationType: EARLIEST
sink:
  kafka:
    bootstrapServers: localhost:9092
    topics: sink_topic