jobName: "Kafka To Doris"
source:
  kafka:
    bootstrapServers: localhost:9092
    topics: topic-product
    groupId: group-2024-10-28
    offsetInitializationType: EARLIEST
sink:
  doris:
    fenodes: localhost:8030
    table: database.product
    username: root
    password: password