jobName: "Two Kafka To Doris"
source:
  kafka-product:
    bootstrapServers: localhost:9092
    topics: topic-product
    groupId: group-2024-10-28
    offsetInitializationType: EARLIEST
  kafka-sale:
    bootstrapServers: localhost:9092
    topics: topic-sale
    groupId: group-2024-10-28
    offsetInitializationType: EARLIEST
sink:
  doris:
    fenodes: localhost:8030
    table: database.sale_report
    username: root
    password: password